title: 光子CI之旅
author: kuuyee
encoding: UTF-8

asciidoc:
  engine: asciidoctor

profiles:
  development:
    base_url: /
#    disqus_developer: true
    dev: true
  production:
    base_url: http://kuuyee.github.io/
    deploy:
      host: github_pages
      branch: master

#google_analytics: UA-3479508-6
#flattr_username: epbernard
#disqus: emmanuelbernard-com
