encoding: UTF-8
title: 光子CI之旅
<<<<<<< HEAD
author: kuuyee 

asciidoc:
  engine: asciidoctor
=======
author: Hibernate Team
>>>>>>> parent of 7636fc3... del all

profiles:
  development:
    base_url: /
#    disqus_developer: true
    dev: true
  production:
<<<<<<< HEAD
    base_url: http://kuuyee.github.io/
    deploy: 
      host: github_pages 
      branch: master
=======
    base_url: http://in.relation.to/

#google_analytics: UA-3479508-6
#flattr_username: epbernard
#disqus: emmanuelbernard-com
>>>>>>> parent of 7636fc3... del all
