encoding: UTF-8
title: 光子CI之旅
author: kuuyee 

asciidoctor:
  :attributes:
    source-highlighter: coderay
    coderay-css: style

profiles:
  development:
    base_url: /
#    disqus_developer: true
    dev: true
  production:
    base_url: http://kuuyee.github.io/
    deploy: 
      host: github_pages 
      branch: master
